# Generated by Django 6.1 on 2026-08-22 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=50, unique=True, verbose_name='Número de sala')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(verbose_name='Fecha de la sesión')),
                ('hora_sesion', models.TimeField(verbose_name='Hora de la sesión')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='pelicula.pelicula', verbose_name='Película')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='sala.sala', verbose_name='Sala')),
            ],
        ),
    ]
