# Generated by Django 6.1 on 2026-08-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesiones'},
        ),
    ]
