# Generated by Django 6.1 on 2026-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_alter_pelicula_portada_imagen'),
        ('sala', '0002_alter_sesion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fecha_sesion', 'hora_sesion'], 'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('sala', 'fecha_sesion', 'hora_sesion'), name='unique_sesion_sala_horario'),
        ),
    ]
