# Generated by Django 6.1 on 2026-08-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50, verbose_name='Nombre Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada_imagen', models.ImageField(blank=True, null=True, upload_to='pelicula/')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.director')),
                ('genero', models.ManyToManyField(to='pelicula.genero')),
            ],
        ),
    ]
