# Generated by Django 6.1 on 2026-08-24 17:35

import pelicula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_lanzamiento',
            field=models.DateField(validators=[pelicula.models.validar_fecha_lanzamiento], verbose_name='Fecha de lanzamiento'),
        ),
    ]
