# Generated by Django 6.1 on 2026-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_alter_pelicula_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='./pelicula'),
        ),
    ]
